--  Session #1:
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;

SELECT rating FROM pizzeria WHERE name = 'Pizza Hut';

--  Session #2:
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
UPDATE pizzeria SET rating = 3.6 WHERE name = 'Pizza Hut';
COMMIT;

-- Session #1:
SELECT rating FROM pizzeria WHERE name = 'Pizza Hut';
COMMIT;
